# Generated by Django 2.2 on 2019-07-14 08:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hosts_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='password',
            field=models.CharField(default=datetime.datetime(2019, 7, 14, 8, 33, 25, 119302, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(default=22),
        ),
    ]
